version: "3.9"

services:
  node:
    build: .
    env_file:
      - .env
    command: node dist/server/index.js
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./src/:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
    depends_on:
      - mongodb
  mongodb:
    image: mongo:6.0.2
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "27017"

volumes:
  db: